genBTC FileTime: genBTC.FileTime.Classes.Native.NativeSelect Class Reference
genBTC.FileTime.Classes.Native.NativeSelect Class Reference
Data Structures
struct LVITEM
Public Member Functions
static IntPtr SendMessageLVItem (IntPtr hWnd, int msg, int wParam, ref LVITEM lvi)
Static Public Member Functions
static void SelectAllItems (ListView list)
Select all rows on the given listview
static void DeselectAllItems (ListView list)
Deselect all rows on the given listview
static int InvertSelection (ListView list)
Invert selection on all rows on the listview and cleanup the focus line.
static void SetItemState (ListView list, int itemIndex, int mask, int value)
Set the item state on the given item
Private Attributes
const int LVM_FIRST = 0x1000
const int LVM_SETITEMSTATE = LVM_FIRST + 43
Detailed Description
Definition at line 7 of file NativeSelect.cs.
Member Function Documentation
static IntPtr genBTC.FileTime.Classes.Native.NativeSelect.SendMessageLVItem (IntPtr hWnd, int msg, int wParam, ref LVITEM lvi)
static void genBTC.FileTime.Classes.Native.NativeSelect.SelectAllItems (ListView list) inline static
Select all rows on the given listview
Parameters
list The listview whose items are to be selected
Definition at line 17 of file NativeSelect.cs.
Referenced by genBTC.FileTime.Forms.Form_Confirm.listView_selectAllToolStripMenuItem_Click().
static void genBTC.FileTime.Classes.Native.NativeSelect.DeselectAllItems (ListView list) inline static
Deselect all rows on the given listview
Parameters
list The listview whose items are to be deselected
Definition at line 28 of file NativeSelect.cs.
Referenced by genBTC.FileTime.Forms.Form_Confirm.listView_deSelectAllToolStripMenuItem_Click().
static int genBTC.FileTime.Classes.Native.NativeSelect.InvertSelection (ListView list) inline static
Invert selection on all rows on the listview and cleanup the focus line.
Parameters
list The listview whose items are to be deselected
Returns
int lastselectedindex (focus line index #)
Definition at line 40 of file NativeSelect.cs.
Referenced by genBTC.FileTime.Forms.Form_Confirm.listView_invertSelectionToolStripMenuItem_Click().
static void genBTC.FileTime.Classes.Native.NativeSelect.SetItemState (ListView list, int itemIndex, int mask, int value) inline static
Set the item state on the given item
Parameters
list The listview whose item's state is to be changed
itemIndex The index of the item to be changed
mask Which bits of the value are to be set?
value The value to be set
Definition at line 66 of file NativeSelect.cs.
Field Documentation
const int genBTC.FileTime.Classes.Native.NativeSelect.LVM_FIRST = 0x1000 private
Definition at line 9 of file NativeSelect.cs.
const int genBTC.FileTime.Classes.Native.NativeSelect.LVM_SETITEMSTATE = LVM_FIRST + 43 private
Definition at line 10 of file NativeSelect.cs.
The documentation for this class was generated from the following file:
NativeSelect.cs