genBTC FileTime: genBTC.FileTime.Models.DataModel Class Reference
genBTC.FileTime.Models.DataModel Class Reference
Static Public Member Functions
static NameDateStruct GetCmaTimesFromFilesystem (string pathName)
Display the date and time of the selected file (also works on Directories)
Data Fields
int fixreadonlyActive = 0
the fixreadonly fixreadonlyActive files count (checked in between fix and unfix)
Package Functions
DataModel ()
Constructor
void Clear (bool resetList)
Clear contents Dir + File lists
List< string > PopulateFileList (string path)
List< string > PopulateDirList (string path)
void DisplayContentsList (bool checkboxRecurse, string labelname, bool filesonly=true)
Display subfiles and subdirectories in the right panel listview and show a file icon
DateTime DecideWhichTimeMode1 (string path)
Returns a DateTime after examining the radiobuttons/checkboxes to specify the logic behavior.
DateTime DecideTimeFromSubdirOrSubfile (string path)
Check all the subdirs or subfiles. And decide the time. Called from above: DecideWhichTimeMode1() { radioGroupBox3_UseTimeFrom
void RecurseSubDirectoryMode1 (string directoryPath)
Mode 1: Process One directory, with recursive sub-directory support. Calls SetFileDateTime() (Only adds to the confirm list, Form 2 will actually write changes).
void RecurseSubDirectoryMode2 (string directoryPath)
Mode 2: Recursive.
void RecurseSubDirectoryMode3 (string targetPath, string comparePath)
Mode 3: Recursive.
void RecurseSubDirectoryMode1Parent (string directoryPath)
Mode 1P (start at its Parent)
void SetTimeDateEachDirectory (string directoryPath, DateTime fileDateTime)
Set Directory Time
void SetTimeDateEachFile (string directoryPath, DateTime fileDateTime)
Set File Time
void AddONEFiletoConfirmList (string filePath, DateTime fileTime, bool isDirectory)
STATIC. Set the date/time for a single file/directory (This works on files and directories) Go through the list, skipping H,S,R files, and add all the file+date objects to the Confirmation List (Only adds to the confirm list, Form 2 (Confirm) will actually write changes).
void SkipOrAddFile (string path, bool isDirectory)
Tracks H,S,R skipcount. Print a Messagebox Question if trying to skip read only files, and fix RO files if needed
bool DecideTimeRG1and2 (string directoryPath)
NameDateObj DecideWhichTimeMode2 (string directoryPath)
Very long function that does a simple task. Read in the options the user set for the operation, and Decide on the timestamp it should use, by the end we will have a single object with 3 times. This will need to be hit with broad strokes if we attempt to do any more work on the program.
void FixReadonlyResults ()
Show a message box of any files that were cleared of their read-only tag.
void ResetReadOnly ()
Adds the read-only attribute back after it was removed
Package Attributes
List< string > contentsDirList
Main Lists for filenames. Dir , File, Ext
List< string > FilesReadOnlytoFix
Pass a resetList of files that had the read-only attribute fixed, so Form2 can display it
List< NameDateObj > FilestoConfirmList
List of Class to be passed to Form 2 for confirmation of files
ListView listViewContents
ImageList imageListFiles
SkippedHSR Skips
Random random
string CwdPathName
BoolCMA checkboxes
guistatus gui
Private Member Functions
void AddImagesExtsToFileLists (string directoryName)
Fill the contents list window with files's own Icons, given a directory name path
void StoreDateByCMACheckboxes (NameDateObjListViewVMdl currentobject)
Private Attributes
List< string > contentsFileList
List< string > filextlist
NameDateObj thingtoreturn Error - File is Read Only. Continue showing Read-Only notifications?"
Detailed Description
Definition at line 14 of file DataModel.cs.
Constructor & Destructor Documentation
genBTC.FileTime.Models.DataModel.DataModel () inline package
Constructor
Definition at line 40 of file DataModel.cs.
Member Function Documentation
void genBTC.FileTime.Models.DataModel.Clear (bool resetList) inline package
Clear contents Dir + File lists
Definition at line 53 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.ClearOnError().
static NameDateStruct genBTC.FileTime.Models.DataModel.GetCmaTimesFromFilesystem (string pathName) inline static
Display the date and time of the selected file (also works on Directories)
Definition at line 64 of file DataModel.cs.
References genBTC.FileTime.Models.File.
Referenced by genBTC.FileTime.Forms.Form_Main.DisplayCma().
List<string> genBTC.FileTime.Models.DataModel.PopulateFileList (string path) inline package
Definition at line 96 of file DataModel.cs.
References genBTC.FileTime.Models.Directory.
List<string> genBTC.FileTime.Models.DataModel.PopulateDirList (string path) inline package
Definition at line 103 of file DataModel.cs.
References genBTC.FileTime.Models.Directory.
void genBTC.FileTime.Models.DataModel.DisplayContentsList (bool checkboxRecurse, string labelname, bool filesonly = true) inline package
Display subfiles and subdirectories in the right panel listview and show a file icon
Parameters
filesonly Don't show the directories, only files.
Definition at line 116 of file DataModel.cs.
References genBTC.FileTime.Models.Directory, and genBTC.FileTime.Classes.SharedHelper.explorerStringComparer().
Referenced by genBTC.FileTime.Forms.Form_Main.RefreshContentsRightPanel().
void genBTC.FileTime.Models.DataModel.AddImagesExtsToFileLists (string directoryName) inline private
Fill the contents list window with files's own Icons, given a directory name path
Definition at line 164 of file DataModel.cs.
References genBTC.FileTime.Classes.SharedHelper.CurrExten, genBTC.FileTime.Models.Directory, genBTC.FileTime.Models.File, genBTC.FileTime.Classes.SharedHelper.FindCurExt(), genBTC.FileTime.Classes.Native.NativeExtractIcon.GetIcon(), and genBTC.FileTime.Classes.SharedHelper.SyncSettingstoInvisibleFlag().
DateTime genBTC.FileTime.Models.DataModel.DecideWhichTimeMode1 (string path) inline package
Returns a DateTime after examining the radiobuttons/checkboxes to specify the logic behavior.
reqs: (string path), contentsDirList, contentsFileList, guistatus
Definition at line 196 of file DataModel.cs.
References genBTC.FileTime.Models.guistatus.Accessed, genBTC.FileTime.Models.guistatus.Created, genBTC.FileTime.Models.guistatus.dateTimePickerDate, genBTC.FileTime.Models.guistatus.dateTimePickerTime, genBTC.FileTime.Models.guistatus.Modified, genBTC.FileTime.Models.guistatus.radioGroupBox1SpecifyTime, genBTC.FileTime.Models.guistatus.radioGroupBox2CurrentSelect, genBTC.FileTime.Models.guistatus.radioGroupBox3UseTimeFrom, genBTC.FileTime.Models.guistatus.rg2rb1Creation, genBTC.FileTime.Models.guistatus.rg2rb2Modified, and genBTC.FileTime.Models.guistatus.rg2rb3LastAccess.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
DateTime genBTC.FileTime.Models.DataModel.DecideTimeFromSubdirOrSubfile (string path) inline package
Check all the subdirs or subfiles. And decide the time. Called from above: DecideWhichTimeMode1() { radioGroupBox3_UseTimeFrom
Definition at line 228 of file DataModel.cs.
References genBTC.FileTime.Models.File, genBTC.FileTime.Models.guistatus.radioButton1_setfromCreated, genBTC.FileTime.Models.guistatus.radioButton1_useTimefromFile, genBTC.FileTime.Models.guistatus.radioButton1Oldest, genBTC.FileTime.Models.guistatus.radioButton2_setfromModified, genBTC.FileTime.Models.guistatus.radioButton2_useTimefromSubdir, genBTC.FileTime.Models.guistatus.radioButton2Newest, genBTC.FileTime.Models.guistatus.radioButton3_setfromAccessed, genBTC.FileTime.Models.guistatus.radioButton3Random, and genBTC.FileTime.Models.guistatus.radioButton4_setfromRandom.
void genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode1 (string directoryPath) inline package
Mode 1: Process One directory, with recursive sub-directory support. Calls SetFileDateTime() (Only adds to the confirm list, Form 2 will actually write changes).
Parameters
directoryPath Full path to the directory
req, checkBox_Recurse.Checked, checkBoxShouldFiles.Checked
Definition at line 304 of file DataModel.cs.
References genBTC.FileTime.Models.guistatus.checkboxRecurse, and genBTC.FileTime.Models.guistatus.checkboxShouldFiles.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
void genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode2 (string directoryPath) inline package
Mode 2: Recursive.
Parameters
directoryPath Path to start in.
Definition at line 323 of file DataModel.cs.
References genBTC.FileTime.Models.Directory.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
void genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode3 (string targetPath, string comparePath) inline package
Mode 3: Recursive.
Parameters
targetPath Write Path to modify times of.
comparePath Read Path used as source of time data.
Definition at line 353 of file DataModel.cs.
References genBTC.FileTime.Classes.SharedHelper.Seperator, and genBTC.FileTime.Classes.SharedHelper.SeperatorString.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpMode3().
void genBTC.FileTime.Models.DataModel.StoreDateByCMACheckboxes (NameDateObjListViewVMdl currentobject) inline private
Definition at line 441 of file DataModel.cs.
References genBTC.FileTime.Models.BoolCMA.A, genBTC.FileTime.mViewModels.NameDateObjListViewVMdl.Accessed, genBTC.FileTime.Models.BoolCMA.C, genBTC.FileTime.mViewModels.NameDateObjListViewVMdl.Created, genBTC.FileTime.Models.BoolCMA.M, and genBTC.FileTime.mViewModels.NameDateObjListViewVMdl.Modified.
void genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode1Parent (string directoryPath) inline package
Mode 1P (start at its Parent)
Definition at line 454 of file DataModel.cs.
References genBTC.FileTime.Models.Directory.
void genBTC.FileTime.Models.DataModel.SetTimeDateEachDirectory (string directoryPath, DateTime fileDateTime) inline package
Set Directory Time
Definition at line 471 of file DataModel.cs.
References genBTC.FileTime.Models.Directory, and genBTC.FileTime.Classes.SharedHelper.explorerStringComparer().
void genBTC.FileTime.Models.DataModel.SetTimeDateEachFile (string directoryPath, DateTime fileDateTime) inline package
Set File Time
Definition at line 492 of file DataModel.cs.
References genBTC.FileTime.Models.Directory, and genBTC.FileTime.Classes.SharedHelper.explorerStringComparer().
void genBTC.FileTime.Models.DataModel.AddONEFiletoConfirmList (string filePath, DateTime fileTime, bool isDirectory) inline package
STATIC. Set the date/time for a single file/directory (This works on files and directories) Go through the list, skipping H,S,R files, and add all the file+date objects to the Confirmation List (Only adds to the confirm list, Form 2 (Confirm) will actually write changes).
Parameters
filePath Full path to the file/directory
fileTime Date/Time to set the file/directory
isDirectory Is this a directory???
Definition at line 513 of file DataModel.cs.
References genBTC.FileTime.Models.BoolCMA.A, genBTC.FileTime.Classes.SharedHelper.Bool2Int(), genBTC.FileTime.Models.BoolCMA.C, and genBTC.FileTime.Models.BoolCMA.M.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
void genBTC.FileTime.Models.DataModel.SkipOrAddFile (string path, bool isDirectory) inline package
Tracks H,S,R skipcount. Print a Messagebox Question if trying to skip read only files, and fix RO files if needed
Definition at line 536 of file DataModel.cs.
References genBTC.FileTime.Properties.Settings.Default, genBTC.FileTime.Models.File, genBTC.FileTime.Models.SkippedHSR.H, genBTC.FileTime.Models.SkippedHSR.R, genBTC.FileTime.Models.SkippedHSR.S, genBTC.FileTime.Properties.Settings.ShowNoticesReadOnly, genBTC.FileTime.Properties.Settings.SkipHidden, genBTC.FileTime.Properties.Settings.SkipReadOnly, and genBTC.FileTime.Properties.Settings.SkipSystem.
bool genBTC.FileTime.Models.DataModel.DecideTimeRG1and2 (string directoryPath) inline package
Definition at line 583 of file DataModel.cs.
References genBTC.FileTime.Models.NameDateObj.Accessed, genBTC.FileTime.Models.guistatus.Accessed, genBTC.FileTime.Models.NameDateObj.Created, genBTC.FileTime.Models.guistatus.Created, genBTC.FileTime.Models.guistatus.dateTimePickerDate, genBTC.FileTime.Models.guistatus.dateTimePickerTime, genBTC.FileTime.Models.NameDateObj.Modified, genBTC.FileTime.Models.guistatus.Modified, genBTC.FileTime.Models.NameDateObj.Name, genBTC.FileTime.Models.guistatus.PathName, genBTC.FileTime.Models.guistatus.radioGroupBox1SpecifyTime, and genBTC.FileTime.Models.guistatus.radioGroupBox2CurrentSelect.
NameDateObj genBTC.FileTime.Models.DataModel.DecideWhichTimeMode2 (string directoryPath) inline package
Very long function that does a simple task. Read in the options the user set for the operation, and Decide on the timestamp it should use, by the end we will have a single object with 3 times. This will need to be hit with broad strokes if we attempt to do any more work on the program.
Definition at line 615 of file DataModel.cs.
References genBTC.FileTime.Models.NameDateObj.Accessed, genBTC.FileTime.Models.NameDateObj.Created, genBTC.FileTime.Models.Directory, genBTC.FileTime.Models.File, genBTC.FileTime.Models.NameDateObj.Modified, genBTC.FileTime.Models.NameDateObj.Name, genBTC.FileTime.Models.guistatus.radioButton1_useTimefromFile, genBTC.FileTime.Models.guistatus.radioButton1Oldest, genBTC.FileTime.Models.guistatus.radioButton2_useTimefromSubdir, genBTC.FileTime.Models.guistatus.radioButton2Newest, genBTC.FileTime.Models.guistatus.radioButton3Random, genBTC.FileTime.Models.guistatus.radioGroupBox3UseTimeFrom, and genBTC.FileTime.Classes.SharedHelper.SyncSettingstoInvisibleFlag().
void genBTC.FileTime.Models.DataModel.FixReadonlyResults () inline package
Show a message box of any files that were cleared of their read-only tag.
Definition at line 782 of file DataModel.cs.
References genBTC.FileTime.Models.File, and genBTC.FileTime.Classes.SharedHelper.RemoveAttributes().
Referenced by genBTC.FileTime.Forms.Form_Confirm.MakeListView(), and genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
void genBTC.FileTime.Models.DataModel.ResetReadOnly () inline package
Adds the read-only attribute back after it was removed
Definition at line 814 of file DataModel.cs.
References genBTC.FileTime.Models.File.
Referenced by genBTC.FileTime.Forms.Form_Confirm.Form_Confirm_FormClosing().
Field Documentation
List<string> genBTC.FileTime.Models.DataModel.contentsDirList package
Main Lists for filenames. Dir , File, Ext
Definition at line 18 of file DataModel.cs.
List<string> genBTC.FileTime.Models.DataModel.contentsFileList private
Definition at line 18 of file DataModel.cs.
List<string> genBTC.FileTime.Models.DataModel.filextlist private
Definition at line 18 of file DataModel.cs.
List<string> genBTC.FileTime.Models.DataModel.FilesReadOnlytoFix package
Pass a resetList of files that had the read-only attribute fixed, so Form2 can display it
Definition at line 20 of file DataModel.cs.
int genBTC.FileTime.Models.DataModel.fixreadonlyActive = 0
the fixreadonly fixreadonlyActive files count (checked in between fix and unfix)
Definition at line 22 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2().
List<NameDateObj> genBTC.FileTime.Models.DataModel.FilestoConfirmList package
List of Class to be passed to Form 2 for confirmation of files
Definition at line 24 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Confirm.Form_Confirm_FormClosing(), genBTC.FileTime.Forms.Form_Confirm.MakeListView(), and genBTC.FileTime.Forms.Form_Main.PrepareDataModelForUse().
ListView genBTC.FileTime.Models.DataModel.listViewContents package
Definition at line 26 of file DataModel.cs.
ImageList genBTC.FileTime.Models.DataModel.imageListFiles package
Definition at line 28 of file DataModel.cs.
SkippedHSR genBTC.FileTime.Models.DataModel.Skips package
Definition at line 30 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.LaunchForm2Go(), and genBTC.FileTime.Forms.Form_Main.PrepareDataModelForUse().
Random genBTC.FileTime.Models.DataModel.random package
Definition at line 32 of file DataModel.cs.
string genBTC.FileTime.Models.DataModel.CwdPathName package
Definition at line 33 of file DataModel.cs.
BoolCMA genBTC.FileTime.Models.DataModel.checkboxes package
Definition at line 35 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.checkBox_DateTime_CheckedChanged(), genBTC.FileTime.Forms.Form_Main.PrepareDataModelForUse(), and genBTC.FileTime.Forms.Form_Main.QueryCMAcheckboxes().
guistatus genBTC.FileTime.Models.DataModel.gui package
Definition at line 36 of file DataModel.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.checkBox_Recurse_CheckedChanged(), genBTC.FileTime.Forms.Form_Main.checkBoxShouldFiles_CheckedChanged(), and genBTC.FileTime.Forms.Form_Main.PrepareDataModelForUse().
NameDateObj genBTC.FileTime.Models.DataModel.thingtoreturn Error - File is Read Only. Continue showing Read-Only notifications?" private
Definition at line 582 of file DataModel.cs.
The documentation for this class was generated from the following file:
DataModel.cs