genBTC FileTime: genBTC.FileTime.Classes.SharedHelper Class Reference
genBTC.FileTime.Classes.SharedHelper Class Reference
Public Member Functions
static int StrCmpLogicalW (String x, String y)
Static Public Member Functions
static IComparer< string > explorerStringComparer ()
static bool FindCurExt (String s)
static FileAttributes RemoveAttributes (FileAttributes attributes, FileAttributes attributesToRemove)
static FileAttributes SyncSettingstoInvisibleFlag ()
Reasons to be invisible
static int Bool2Int (bool fileOrDir)
Return 1 if bool=true (Directory) otherwise 0=false (File)
static string OpenFilePicker (string inpath)
Display the Folder Browser Dialog and then display the selected file path and the directories and files in the folder.
Data Fields
List< string > Filextlist = new List<string>()
Static Public Attributes
static readonly char Seperator = Path.DirectorySeparatorChar
static readonly string SeperatorString = Path.DirectorySeparatorChar.ToString()
static readonly string UserDesktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)
static string CurrExten
Detailed Description
Definition at line 12 of file SharedHelper.cs.
Member Function Documentation
static int genBTC.FileTime.Classes.SharedHelper.StrCmpLogicalW (String x, String y)
Referenced by genBTC.FileTime.Classes.ExplorerLikeComparer.Compare(), genBTC.FileTime.Classes.ExpLikeCmpHelperforListView.Compare(), and genBTC.FileTime.Models.NameDateObj.ExplorerLikeSort.Compare().
static IComparer<string> genBTC.FileTime.Classes.SharedHelper.explorerStringComparer () inline static
Definition at line 17 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Models.DataModel.DisplayContentsList(), genBTC.FileTime.Models.DataModel.SetTimeDateEachDirectory(), and genBTC.FileTime.Models.DataModel.SetTimeDateEachFile().
static bool genBTC.FileTime.Classes.SharedHelper.FindCurExt (String s) inline static
Definition at line 29 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Models.DataModel.AddImagesExtsToFileLists(), and genBTC.FileTime.Forms.Form_Confirm.MakeListView().
static FileAttributes genBTC.FileTime.Classes.SharedHelper.RemoveAttributes (FileAttributes attributes, FileAttributes attributesToRemove) inline static
Definition at line 34 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Models.DataModel.FixReadonlyResults().
static FileAttributes genBTC.FileTime.Classes.SharedHelper.SyncSettingstoInvisibleFlag () inline static
Reasons to be invisible
Definition at line 40 of file SharedHelper.cs.
References genBTC.FileTime.Properties.Settings.Default, genBTC.FileTime.Properties.Settings.ShowHidden, genBTC.FileTime.Properties.Settings.ShowReadOnly, and genBTC.FileTime.Properties.Settings.ShowSystem.
Referenced by genBTC.FileTime.Models.DataModel.AddImagesExtsToFileLists(), and genBTC.FileTime.Models.DataModel.DecideWhichTimeMode2().
static int genBTC.FileTime.Classes.SharedHelper.Bool2Int (bool fileOrDir) inline static
Return 1 if bool=true (Directory) otherwise 0=false (File)
Definition at line 49 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Models.DataModel.AddONEFiletoConfirmList(), and genBTC.FileTime.mViewModels.NameDateObjListViewVMdl.NameDateObjListViewVMdl().
static string genBTC.FileTime.Classes.SharedHelper.OpenFilePicker (string inpath) inline static
Display the Folder Browser Dialog and then display the selected file path and the directories and files in the folder.
Definition at line 58 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.button_Browse_Click(), genBTC.FileTime.Forms.Form_Main.button_Update_Click(), and genBTC.FileTime.Forms.Form_Main.menuItem_FileOpen_Click().
Field Documentation
readonly char genBTC.FileTime.Classes.SharedHelper.Seperator = Path.DirectorySeparatorChar static
Definition at line 22 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.explorerTree1_PathChanged(), genBTC.FileTime.Forms.Form_Main.Form_Main_Run(), and genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode3().
readonly string genBTC.FileTime.Classes.SharedHelper.SeperatorString = Path.DirectorySeparatorChar.ToString() static
Definition at line 23 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.explorerTree1_PathChanged(), and genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode3().
readonly string genBTC.FileTime.Classes.SharedHelper.UserDesktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) static
Definition at line 24 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Forms.Form_Main.Form_Main_Run().
string genBTC.FileTime.Classes.SharedHelper.CurrExten static
Definition at line 26 of file SharedHelper.cs.
Referenced by genBTC.FileTime.Models.DataModel.AddImagesExtsToFileLists(), and genBTC.FileTime.Forms.Form_Confirm.MakeListView().
List<string> genBTC.FileTime.Classes.SharedHelper.Filextlist = new List<string>()
Definition at line 27 of file SharedHelper.cs.
The documentation for this class was generated from the following file:
SharedHelper.cs