genBTC FileTime: genBTC.FileTime.Forms.Form_Confirm Class Reference
genBTC.FileTime.Forms.Form_Confirm Class Reference
Form 2, confirms the action and shows filenames and dates
Public Member Functions
void MakeListView ()
turn the NameDateObj lists from Form_Main into the listview on Form_Confirm
Static Public Member Functions
static bool SetTime (int cmaType, string pathName, DateTime newDate)
Function which touches the filesystem to set the dates
Data Fields
ComboBox comboBox1_Created
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Package Functions
Form_Confirm (DataModel f1DataModel)
Form 2 creation and initialization code.
Private Member Functions
void UpdateStatusBar ()
Show current number of files on the status bar line, and store all checkboxes each time Most likely this is being called because the number of items have changed, so make a new list of stored checkboxes.
void Form_Confirm_FormClosing (object sender, FormClosingEventArgs e)
Cleanup. Clear the main form's fileconfirm list if form2 is closed. If the user does not want to clear the list, they can leave the form_Confirm open and access form_Main multiple times to incrementally add to the form_Confirm list.
void button1_Confirm_Click (object sender, EventArgs e)
Confirm Button - Actually finally set the files datetimes, if it matches conditions. Shows a progress bar.
void ThreeComboBox_SelectedChange (object sender, EventArgs e)
void listView_selectAllToolStripMenuItem_Click (object sender, EventArgs e)
void listView_deSelectAllToolStripMenuItem_Click (object sender, EventArgs e)
void listView_invertSelectionToolStripMenuItem_Click (object sender, EventArgs e)
void listView_removeNAOnlysToolStripMenuItem_Click (object sender, EventArgs e)
void listView_condenseMultipleLinesToolStripMenuItem_Click (object sender, EventArgs e)
Combine all the adjacent items which have the same name, and matching blank/nonblank or identical date attributes
void listView_SetDatesOfAllSelecteds (NameDateObj dateToUse)
void listView_RemoveDatesOfAllSelecteds (int menunumber)
void toolStripMenuItem1_ChangeDate_Click (object sender, EventArgs e)
Change Date...
void toolStripMenuItem234_ThreeRemoves_Click (object sender, EventArgs e)
Remove 1=Created,2=Modified,3=Accessed...
void toolStripMenuItem5_unSetALL_Click (object sender, EventArgs e)
void toolStripMenuItem6_RemoveItem_Click (object sender, EventArgs e)
Remove Item from list...
void toolStripMenuItem7_OpenExplorer_Click (object sender, EventArgs e)
Open Explorer to selected path. Supports multi-selection up to 10 items
void listView_RestoreAllCheckboxes ()
restore all the checkboxes at once (not used?)
void listView_RestoreCheckbox (int index)
restore only one checkbox.
void listView_StoreAllCheckboxes ()
Clear list if any, and store entire new list of checkboxes. TODO: could not direct copy the internal array (see comments) - revisit.
void listView_StoreCheckbox (int itemIndex, bool itemChecked)
Change stored value of one checkbox in the checklist storage array. Called multiple times from listView1Confirm_ItemChecked, e is the item being changed.
void listView1Confirm_ItemChecked (object sender, ItemCheckedEventArgs e)
Trick to store/cache item selection checkboxes. Should save time, and improve lag on large lists with large (>25) selections. TODO: revisit this, and invent a better trick for >25 items. TODO: benchmark the store and restore, optimize.
void menuStrip1_Click (object sender, EventArgs e)
Trick to change focus back to the listview when the menu is clicked (so it doesnt go gray)
void listView1Confirm_KeyUp (object sender, KeyEventArgs e)
respond to the delete key, and call the delete context menu
void InitializeComponent ()
void contextMenuStrip1_Opening (object sender, System.ComponentModel.CancelEventArgs e)
Static Private Member Functions
static bool DoConditionalAgeCheck (int cmaType, string pathName, DateTime newDate, bool useNewer, bool useOlder)
Check the radiobuttons, then check the filesystem's existing dates and returns true if files should be modified.
Private Attributes
readonly List< string > _filextlist = new List<string>()
DataModel dataModel
List< bool > _checklist
list of listview items's checkbox state bool values
int _itemsErrorsCount
Count of the number of files/directories that have errors setting the date/time
int _itemsSetCount
Count of the number of files/directories that have been set
System.ComponentModel.IContainer components = null
Required designer variable.
ImageList imageList_Files
Required method for Designer support - do not modify the contents of this method with the code editor.
Label label1
Button button1_Confirm
CustomListView listView1Confirm
ContextMenuStrip rightClickContextMenu1
GroupBox groupBoxConditions
RadioButton radioButton3All
RadioButton radioButton2Older
RadioButton radioButton1Newer
MenuStrip menuStrip1
ToolStripMenuItem editToolStripMenuItem
ToolStripMenuItem selectAllToolStripMenuItem
ToolStripMenuItem deSelectAllToolStripMenuItem
ToolStripMenuItem invertSelectionToolStripMenuItem
ComboBox comboBox2_Modified
ComboBox comboBox3_Accessed
ToolStripMenuItem removeNAOnlysToolStripMenuItem
Label label2
Panel panel1
ColumnHeader ColumnHeader_Name
ColumnHeader ColumnHeader_Created
ColumnHeader ColumnHeader_Modified
ColumnHeader ColumnHeader_Accessed
ToolStripMenuItem toolStripMenuItem1_ChangeDate
ToolStripMenuItem toolStripMenuItem2_UnsetCreated
ToolStripMenuItem toolStripMenuItem3_UnsetModified
ToolStripMenuItem toolStripMenuItem4_UnsetAccessed
ToolStripSeparator toolStripSeparator1
ToolStripMenuItem toolStripMenuItem7_OpenExplorer
StatusStrip statusStrip1
ToolStripProgressBar toolStripProgressBar1
ToolStripStatusLabel toolStripStatusLabel1
ToolStripMenuItem condenseMultipleLinesToolStripMenuItem
ToolStripMenuItem toolStripMenuItem6_RemoveItem
ToolStripMenuItem toolStripMenuItem5_unSetALL
Detailed Description
Form 2, confirms the action and shows filenames and dates
Definition at line 21 of file Form_Confirm.cs.
Constructor & Destructor Documentation
genBTC.FileTime.Forms.Form_Confirm.Form_Confirm (DataModel f1DataModel) inline package
Form 2 creation and initialization code.
Parameters
f1DataModel
Definition at line 41 of file Form_Confirm.cs.
Member Function Documentation
void genBTC.FileTime.Forms.Form_Confirm.MakeListView () inline
turn the NameDateObj lists from Form_Main into the listview on Form_Confirm
use the results as the new data model.
Definition at line 63 of file Form_Confirm.cs.
References genBTC.FileTime.Models.NameDateObj.Accessed, genBTC.FileTime.Models.NameDateObj.Created, genBTC.FileTime.Classes.SharedHelper.CurrExten, genBTC.FileTime.Models.NameDateObj.FileOrDirType, genBTC.FileTime.Models.DataModel.FilestoConfirmList, genBTC.FileTime.Classes.SharedHelper.FindCurExt(), genBTC.FileTime.Models.DataModel.FixReadonlyResults(), genBTC.FileTime.Classes.Native.NativeExtractIcon.GetIcon(), genBTC.FileTime.Models.NameDateObj.Modified, and genBTC.FileTime.Models.NameDateObj.Name.
Referenced by genBTC.FileTime.Forms.Form_Main.LaunchForm2Go().
void genBTC.FileTime.Forms.Form_Confirm.UpdateStatusBar () inline private
Show current number of files on the status bar line, and store all checkboxes each time Most likely this is being called because the number of items have changed, so make a new list of stored checkboxes.
Definition at line 97 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.Form_Confirm_FormClosing (object sender, FormClosingEventArgs e) inline private
Cleanup. Clear the main form's fileconfirm list if form2 is closed. If the user does not want to clear the list, they can leave the form_Confirm open and access form_Main multiple times to incrementally add to the form_Confirm list.
Definition at line 108 of file Form_Confirm.cs.
References genBTC.FileTime.Models.DataModel.FilestoConfirmList, and genBTC.FileTime.Models.DataModel.ResetReadOnly().
static bool genBTC.FileTime.Forms.Form_Confirm.DoConditionalAgeCheck (int cmaType, string pathName, DateTime newDate, bool useNewer, bool useOlder) inline static private
Check the radiobuttons, then check the filesystem's existing dates and returns true if files should be modified.
TODO: Tuple radioButton1Newer radioButton2Older
Definition at line 119 of file Form_Confirm.cs.
References genBTC.FileTime.Models.File.
static bool genBTC.FileTime.Forms.Form_Confirm.SetTime (int cmaType, string pathName, DateTime newDate) inline static
Function which touches the filesystem to set the dates
Notes: Directory works on both files and dirs.
Definition at line 142 of file Form_Confirm.cs.
References genBTC.FileTime.Models.Directory.
void genBTC.FileTime.Forms.Form_Confirm.button1_Confirm_Click (object sender, EventArgs e) inline private
Confirm Button - Actually finally set the files datetimes, if it matches conditions. Shows a progress bar.
Definition at line 163 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.ThreeComboBox_SelectedChange (object sender, EventArgs e) inline private
Definition at line 211 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_selectAllToolStripMenuItem_Click (object sender, EventArgs e) inline private
Definition at line 250 of file Form_Confirm.cs.
References genBTC.FileTime.Classes.Native.NativeSelect.SelectAllItems().
void genBTC.FileTime.Forms.Form_Confirm.listView_deSelectAllToolStripMenuItem_Click (object sender, EventArgs e) inline private
Definition at line 255 of file Form_Confirm.cs.
References genBTC.FileTime.Classes.Native.NativeSelect.DeselectAllItems().
void genBTC.FileTime.Forms.Form_Confirm.listView_invertSelectionToolStripMenuItem_Click (object sender, EventArgs e) inline private
Definition at line 260 of file Form_Confirm.cs.
References genBTC.FileTime.Classes.Native.NativeSelect.InvertSelection().
void genBTC.FileTime.Forms.Form_Confirm.listView_removeNAOnlysToolStripMenuItem_Click (object sender, EventArgs e) inline private
Definition at line 265 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_condenseMultipleLinesToolStripMenuItem_Click (object sender, EventArgs e) inline private
Combine all the adjacent items which have the same name, and matching blank/nonblank or identical date attributes
Definition at line 285 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_SetDatesOfAllSelecteds (NameDateObj dateToUse) inline private
Definition at line 313 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_RemoveDatesOfAllSelecteds (int menunumber) inline private
Definition at line 326 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem1_ChangeDate_Click (object sender, EventArgs e) inline private
Change Date...
Definition at line 336 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem234_ThreeRemoves_Click (object sender, EventArgs e) inline private
Remove 1=Created,2=Modified,3=Accessed...
Definition at line 352 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem5_unSetALL_Click (object sender, EventArgs e) inline private
Definition at line 368 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem6_RemoveItem_Click (object sender, EventArgs e) inline private
Remove Item from list...
Definition at line 384 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem7_OpenExplorer_Click (object sender, EventArgs e) inline private
Open Explorer to selected path. Supports multi-selection up to 10 items
Definition at line 423 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_RestoreAllCheckboxes () inline private
restore all the checkboxes at once (not used?)
Definition at line 442 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_RestoreCheckbox (int index) inline private
restore only one checkbox.
Definition at line 457 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_StoreAllCheckboxes () inline private
Clear list if any, and store entire new list of checkboxes. TODO: could not direct copy the internal array (see comments) - revisit.
Definition at line 470 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView_StoreCheckbox (int itemIndex, bool itemChecked) inline private
Change stored value of one checkbox in the checklist storage array. Called multiple times from listView1Confirm_ItemChecked, e is the item being changed.
Definition at line 485 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView1Confirm_ItemChecked (object sender, ItemCheckedEventArgs e) inline private
Trick to store/cache item selection checkboxes. Should save time, and improve lag on large lists with large (>25) selections. TODO: revisit this, and invent a better trick for >25 items. TODO: benchmark the store and restore, optimize.
Definition at line 501 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.menuStrip1_Click (object sender, EventArgs e) inline private
Trick to change focus back to the listview when the menu is clicked (so it doesnt go gray)
Definition at line 524 of file Form_Confirm.cs.
void genBTC.FileTime.Forms.Form_Confirm.listView1Confirm_KeyUp (object sender, KeyEventArgs e) inline private
respond to the delete key, and call the delete context menu
Definition at line 530 of file Form_Confirm.cs.
override void genBTC.FileTime.Forms.Form_Confirm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 18 of file Form_Confirm.Designer.cs.
void genBTC.FileTime.Forms.Form_Confirm.InitializeComponent () inline private
Definition at line 37 of file Form_Confirm.Designer.cs.
void genBTC.FileTime.Forms.Form_Confirm.contextMenuStrip1_Opening (object sender, System.ComponentModel.CancelEventArgs e) inline private
Definition at line 480 of file Form_Confirm.Designer.cs.
Field Documentation
readonly List<string> genBTC.FileTime.Forms.Form_Confirm._filextlist = new List<string>() private
Definition at line 26 of file Form_Confirm.cs.
DataModel genBTC.FileTime.Forms.Form_Confirm.dataModel private
Definition at line 27 of file Form_Confirm.cs.
List<bool> genBTC.FileTime.Forms.Form_Confirm._checklist private
list of listview items's checkbox state bool values
Definition at line 30 of file Form_Confirm.cs.
int genBTC.FileTime.Forms.Form_Confirm._itemsErrorsCount private
Count of the number of files/directories that have errors setting the date/time
Definition at line 33 of file Form_Confirm.cs.
int genBTC.FileTime.Forms.Form_Confirm._itemsSetCount private
Count of the number of files/directories that have been set
Definition at line 36 of file Form_Confirm.cs.
System.ComponentModel.IContainer genBTC.FileTime.Forms.Form_Confirm.components = null private
Required designer variable.
Definition at line 12 of file Form_Confirm.Designer.cs.
ImageList genBTC.FileTime.Forms.Form_Confirm.imageList_Files private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 33 of file Form_Confirm.Designer.cs.
Label genBTC.FileTime.Forms.Form_Confirm.label1 private
Definition at line 34 of file Form_Confirm.Designer.cs.
Button genBTC.FileTime.Forms.Form_Confirm.button1_Confirm private
Definition at line 35 of file Form_Confirm.Designer.cs.
CustomListView genBTC.FileTime.Forms.Form_Confirm.listView1Confirm private
Definition at line 487 of file Form_Confirm.Designer.cs.
ContextMenuStrip genBTC.FileTime.Forms.Form_Confirm.rightClickContextMenu1 private
Definition at line 488 of file Form_Confirm.Designer.cs.
GroupBox genBTC.FileTime.Forms.Form_Confirm.groupBoxConditions private
Definition at line 490 of file Form_Confirm.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Confirm.radioButton3All private
Definition at line 491 of file Form_Confirm.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Confirm.radioButton2Older private
Definition at line 492 of file Form_Confirm.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Confirm.radioButton1Newer private
Definition at line 493 of file Form_Confirm.Designer.cs.
MenuStrip genBTC.FileTime.Forms.Form_Confirm.menuStrip1 private
Definition at line 494 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.editToolStripMenuItem private
Definition at line 495 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.selectAllToolStripMenuItem private
Definition at line 496 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.deSelectAllToolStripMenuItem private
Definition at line 497 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.invertSelectionToolStripMenuItem private
Definition at line 498 of file Form_Confirm.Designer.cs.
ComboBox genBTC.FileTime.Forms.Form_Confirm.comboBox1_Created
Definition at line 499 of file Form_Confirm.Designer.cs.
ComboBox genBTC.FileTime.Forms.Form_Confirm.comboBox2_Modified private
Definition at line 500 of file Form_Confirm.Designer.cs.
ComboBox genBTC.FileTime.Forms.Form_Confirm.comboBox3_Accessed private
Definition at line 501 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.removeNAOnlysToolStripMenuItem private
Definition at line 502 of file Form_Confirm.Designer.cs.
Label genBTC.FileTime.Forms.Form_Confirm.label2 private
Definition at line 503 of file Form_Confirm.Designer.cs.
Panel genBTC.FileTime.Forms.Form_Confirm.panel1 private
Definition at line 504 of file Form_Confirm.Designer.cs.
ColumnHeader genBTC.FileTime.Forms.Form_Confirm.ColumnHeader_Name private
Definition at line 505 of file Form_Confirm.Designer.cs.
ColumnHeader genBTC.FileTime.Forms.Form_Confirm.ColumnHeader_Created private
Definition at line 506 of file Form_Confirm.Designer.cs.
ColumnHeader genBTC.FileTime.Forms.Form_Confirm.ColumnHeader_Modified private
Definition at line 507 of file Form_Confirm.Designer.cs.
ColumnHeader genBTC.FileTime.Forms.Form_Confirm.ColumnHeader_Accessed private
Definition at line 508 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem1_ChangeDate private
Definition at line 509 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem2_UnsetCreated private
Definition at line 510 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem3_UnsetModified private
Definition at line 511 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem4_UnsetAccessed private
Definition at line 512 of file Form_Confirm.Designer.cs.
ToolStripSeparator genBTC.FileTime.Forms.Form_Confirm.toolStripSeparator1 private
Definition at line 513 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem7_OpenExplorer private
Definition at line 514 of file Form_Confirm.Designer.cs.
StatusStrip genBTC.FileTime.Forms.Form_Confirm.statusStrip1 private
Definition at line 515 of file Form_Confirm.Designer.cs.
ToolStripProgressBar genBTC.FileTime.Forms.Form_Confirm.toolStripProgressBar1 private
Definition at line 516 of file Form_Confirm.Designer.cs.
ToolStripStatusLabel genBTC.FileTime.Forms.Form_Confirm.toolStripStatusLabel1 private
Definition at line 517 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.condenseMultipleLinesToolStripMenuItem private
Definition at line 518 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem6_RemoveItem private
Definition at line 519 of file Form_Confirm.Designer.cs.
ToolStripMenuItem genBTC.FileTime.Forms.Form_Confirm.toolStripMenuItem5_unSetALL private
Definition at line 520 of file Form_Confirm.Designer.cs.
The documentation for this class was generated from the following files:
Form_Confirm.cs
Form_Confirm.Designer.cs