genBTC FileTime: genBTC.FileTime.Forms.Form_Main Class Reference
genBTC.FileTime.Forms.Form_Main Class Reference
GUI : Main Form Window of the Program.
Public Member Functions
Form_Main ()
Init the main startup form
void RefreshDataBinding_labelFPath ()
The Text Box Data Binding is rebound.
Data Fields
Form_Confirm Confirmation
Stub for Form 2 to be accessed once it is opened.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Package Functions
void RefreshContentsRightPanel ()
Wrapper for DisplayContentsList that manages imageList and listView resources automatically. TODO: Can be moved to model later.
Package Attributes
DataModel _dataModel
A model of the data. Self sufficient.
Properties
string CwdPathName [get, set]
Public Setter to the private variable in Datamodel.
Private Member Functions
guistatus GetGUIRadioButtonStatusData ()
void Form_Main_Load (object sender, EventArgs e)
After the InitializeComponent() loads the designer, the designer will fire an event handler signifying its done loading
void Form_Main_Run ()
At this point we can run our code (that wants to interact with our designer GUI).
void menuItem_FileOpen_Click (object sender, EventArgs e)
void menuItem_FileExit_Click (object sender, EventArgs e)
void menuItem_HelpContents_Click (object sender, EventArgs e)
void menuItem_HelpAbout_Click (object sender, EventArgs e)
void menuItem_Preferences_Click (object sender, EventArgs e)
Create and initialize preferences
void label1_CreationDate_Click (object sender, EventArgs e)
void label2_ModifiedDate_Click (object sender, EventArgs e)
void label3_AccessDate_Click (object sender, EventArgs e)
void tabControl1_Selected (object sender, TabControlEventArgs e)
void tabControl1_MouseHover (object sender, EventArgs e)
void ItemSelectionChangedTimer_Tick (object sender, EventArgs e)
Timer Event function. Used to prevent the currently selected Textboxes for the 3 Times from blanking when an item selection is changed. Assosciated with listView_Contents_ItemSelectionChanged() — Fires after some delay (SELECTION_TIMEOUT ms) and if there still is nothing selected, calls CallDisplayCma().
void listView_Contents_ItemSelectionChanged (object sender, ListViewItemSelectionChangedEventArgs e)
The Contents listview (right) selection has changed. Timer-based solution - block re-selection within SELECTION_TIMEOUTms
void checkBox_DateTime_CheckedChanged (object sender, EventArgs e)
Creation,Modified,Accessed Checkbox selection changed. Only enable the update button if something is selected
void explorerTree1_PathChanged (object sender, EventArgs e)
Update the textlabel box for FilePath when the Explorer Tree path changes. (making sure it always ends in a \ seperator). Also causes a re-render of Contents!
BoolCMA QueryCMAcheckboxes ()
Return the value of the checkboxes "CMA Time"
void checkBox_Recurse_CheckedChanged (object sender, EventArgs e)
void checkBoxShouldFiles_CheckedChanged (object sender, EventArgs e)
void ClearOnError ()
Clear both ListViews and the three data container lists, blanks the selected date, and erases the top current dir textbox.
void DisplayCma (string path)
Display file's times in the Tri-Textbox bottom UI for the currently selected file.
void CallDisplayCma (ListView listViewContents, string srcPath)
Update the GUI - Display the DateTime for the currently selected file. Calls DisplayCma
void button_Browse_Click (object sender, EventArgs e)
void button_Update_Click (object sender, EventArgs e)
void StartUpMode3 (string targetPath, string comparePath)
Mode 3. Recursive, file Tree time compare mode. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-compare-the-contents-of-two-folders-linq
void PrepareDataModelForUse ()
Resets the files-to-confirm list, Skips count, reads GUIstatus data (radios), reads CMA checkboxes (lazy/dupe gui fields)
void StartUpBothModes1And2 (int mode2, string startingdir)
Launches Mode 1 and Mode 2. This runs a LONG process on the folders/files. It decides which time to use, then adds them to the confirm list to be handled by the form_confirm window (part2). Cant move into the model. This is a nice staging point place for making EVERYTHING happen.
void LaunchForm2Go ()
Show files to be changed in the confirmation window (Show Form 2)
void label_folderCompareRadioButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
readonly Timer _itemSelectionChangedTimer = new Timer()
a Timer to keep track of the selected line, prevents clicking too fast (timeout)
const int SELECTION_TIMEOUT = 100
Timeout in ms for ListView selection-box's repeat mouse click rejection
System.ComponentModel.IContainer components = null
Required designer variable.
Button button_Browse
MainMenu mainMenu_Main
MenuItem menuItem_FileExit
MenuItem menuItem_Help
MenuItem menuItem_HelpAbout
Button button_GoUpdate
MenuItem menuItem_FileOpen
CheckBox checkBox_CreationDateTime
CheckBox checkBox_AccessedDateTime
CheckBox checkBox_ModifiedDateTime
Label label_FPath
DateTimePicker dateTimePicker_Time
ImageList imageList_Files
CheckBox checkBox_Recurse
MenuItem menuItem_File
MenuItem menuItem_FileBar01
MenuItem menuItem_HelpContents
MenuItem menuItem_HelpBar01
Label label_FilePathHeading
DateTimePicker dateTimePicker_Date
ListView listView_Contents
ColumnHeader listview_ContentsColumHeader1
CheckBox checkBoxShouldFiles
GroupBox groupBoxCMA
RadioButton radioButton1_CreationDate
Label label_CreationTime
RadioButton radioButton2_ModifiedDate
Label label_ModificationTime
RadioButton radioButton3_AccessedDate
Label label_AccessedTime
RadioButton radioButton3_setfromAccessed
RadioButton radioButton2_setfromModified
RadioButton radioButton1_setfromCreation
UIToolbox.RadioButtonPanel radioButtonPanel1_DecideWhichTime
UIToolbox.RadioGroupBox radioGroupBox3_UseTimeFrom
UIToolbox.RadioGroupBox radioGroupBox1_SpecifyTime
Panel panel1
Panel panel2
RadioButton radioButton3_Random
RadioButton radioButton2_Newest
RadioButton radioButton1_Oldest
UIToolbox.RadioGroupBox radioGroupBox2_CurrentSelectionTime
Label label3_AccessedDate
Label label2_ModifiedDate
Label label1_CreationDate
UIToolbox.RadioButtonPanel radioButtonPanel2
Panel panel3
RadioButton radioButton2_useTimefromSubdir
RadioButton radioButton1_useTimefromFile
RadioButton radioButton4_setfromRandom
Label labelHidden_PathName
MenuItem menuItem_Preferences
TabControl tabControl1
TabPage tabPage1
TabPage tabPage2
ToolTip toolTip1
WindowsExplorer.ExplorerTree explorerTree1
SplitContainer splitContainer1
UIToolbox.RadioGroupBox radioGroupBox4_pickFolderForCompare
Label label_folderCompareRadioButton
BindingSource dataModelBindingSource
Detailed Description
GUI : Main Form Window of the Program.
Definition at line 31 of file Form_Main.cs.
Constructor & Destructor Documentation
genBTC.FileTime.Forms.Form_Main.Form_Main () inline
Init the main startup form
Definition at line 81 of file Form_Main.cs.
Member Function Documentation
guistatus genBTC.FileTime.Forms.Form_Main.GetGUIRadioButtonStatusData () inline private
Definition at line 34 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.Form_Main_Load (object sender, EventArgs e) inline private
After the InitializeComponent() loads the designer, the designer will fire an event handler signifying its done loading
Definition at line 91 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.RefreshDataBinding_labelFPath () inline
The Text Box Data Binding is rebound.
Definition at line 111 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.Form_Main_Run () inline private
At this point we can run our code (that wants to interact with our designer GUI).
Definition at line 120 of file Form_Main.cs.
References genBTC.FileTime.Properties.Settings.Default, genBTC.FileTime.Classes.SharedHelper.Seperator, genBTC.FileTime.Properties.Settings.StartupDir, genBTC.FileTime.Classes.SharedHelper.UserDesktop, and genBTC.FileTime.Properties.Settings.useStartupDir.
void genBTC.FileTime.Forms.Form_Main.menuItem_FileOpen_Click (object sender, EventArgs e) inline private
Definition at line 140 of file Form_Main.cs.
References genBTC.FileTime.Classes.SharedHelper.OpenFilePicker().
void genBTC.FileTime.Forms.Form_Main.menuItem_FileExit_Click (object sender, EventArgs e) inline private
Definition at line 145 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.menuItem_HelpContents_Click (object sender, EventArgs e) inline private
Definition at line 150 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.menuItem_HelpAbout_Click (object sender, EventArgs e) inline private
Definition at line 155 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.menuItem_Preferences_Click (object sender, EventArgs e) inline private
Create and initialize preferences
Definition at line 162 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.label1_CreationDate_Click (object sender, EventArgs e) inline private
Definition at line 172 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.label2_ModifiedDate_Click (object sender, EventArgs e) inline private
Definition at line 177 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.label3_AccessDate_Click (object sender, EventArgs e) inline private
Definition at line 182 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.tabControl1_Selected (object sender, TabControlEventArgs e) inline private
Definition at line 187 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.tabControl1_MouseHover (object sender, EventArgs e) inline private
Definition at line 195 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.ItemSelectionChangedTimer_Tick (object sender, EventArgs e) inline private
Timer Event function. Used to prevent the currently selected Textboxes for the 3 Times from blanking when an item selection is changed. Assosciated with listView_Contents_ItemSelectionChanged() — Fires after some delay (SELECTION_TIMEOUT ms) and if there still is nothing selected, calls CallDisplayCma().
Definition at line 211 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.listView_Contents_ItemSelectionChanged (object sender, ListViewItemSelectionChangedEventArgs e) inline private
The Contents listview (right) selection has changed. Timer-based solution - block re-selection within SELECTION_TIMEOUTms
Definition at line 220 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.checkBox_DateTime_CheckedChanged (object sender, EventArgs e) inline private
Creation,Modified,Accessed Checkbox selection changed. Only enable the update button if something is selected
Definition at line 235 of file Form_Main.cs.
References genBTC.FileTime.Models.BoolCMA.A, genBTC.FileTime.Models.BoolCMA.C, genBTC.FileTime.Models.DataModel.checkboxes, and genBTC.FileTime.Models.BoolCMA.M.
void genBTC.FileTime.Forms.Form_Main.explorerTree1_PathChanged (object sender, EventArgs e) inline private
Update the textlabel box for FilePath when the Explorer Tree path changes. (making sure it always ends in a \ seperator). Also causes a re-render of Contents!
Definition at line 246 of file Form_Main.cs.
References genBTC.FileTime.Classes.SharedHelper.Seperator, and genBTC.FileTime.Classes.SharedHelper.SeperatorString.
void genBTC.FileTime.Forms.Form_Main.RefreshContentsRightPanel () inline package
Wrapper for DisplayContentsList that manages imageList and listView resources automatically. TODO: Can be moved to model later.
Definition at line 267 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.DisplayContentsList().
BoolCMA genBTC.FileTime.Forms.Form_Main.QueryCMAcheckboxes () inline private
Return the value of the checkboxes "CMA Time"
Definition at line 277 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.checkboxes.
void genBTC.FileTime.Forms.Form_Main.checkBox_Recurse_CheckedChanged (object sender, EventArgs e) inline private
Definition at line 289 of file Form_Main.cs.
References genBTC.FileTime.Models.guistatus.checkboxRecurse, and genBTC.FileTime.Models.DataModel.gui.
void genBTC.FileTime.Forms.Form_Main.checkBoxShouldFiles_CheckedChanged (object sender, EventArgs e) inline private
Definition at line 294 of file Form_Main.cs.
References genBTC.FileTime.Models.guistatus.checkboxShouldFiles, and genBTC.FileTime.Models.DataModel.gui.
void genBTC.FileTime.Forms.Form_Main.ClearOnError () inline private
Clear both ListViews and the three data container lists, blanks the selected date, and erases the top current dir textbox.
Definition at line 302 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.Clear().
void genBTC.FileTime.Forms.Form_Main.DisplayCma (string path) inline private
Display file's times in the Tri-Textbox bottom UI for the currently selected file.
Definition at line 313 of file Form_Main.cs.
References genBTC.FileTime.Models.NameDateStruct.Accessed, genBTC.FileTime.Models.NameDateStruct.Created, genBTC.FileTime.Models.DataModel.GetCmaTimesFromFilesystem(), genBTC.FileTime.Models.NameDateStruct.HiddenPathName, genBTC.FileTime.Models.NameDateStruct.Modified, and genBTC.FileTime.Models.NameDateStruct.Selected.
void genBTC.FileTime.Forms.Form_Main.CallDisplayCma (ListView listViewContents, string srcPath) inline private
Update the GUI - Display the DateTime for the currently selected file. Calls DisplayCma
Definition at line 328 of file Form_Main.cs.
void genBTC.FileTime.Forms.Form_Main.button_Browse_Click (object sender, EventArgs e) inline private
Definition at line 343 of file Form_Main.cs.
References genBTC.FileTime.Classes.SharedHelper.OpenFilePicker().
void genBTC.FileTime.Forms.Form_Main.button_Update_Click (object sender, EventArgs e) inline private
Definition at line 351 of file Form_Main.cs.
References genBTC.FileTime.Classes.SharedHelper.OpenFilePicker().
void genBTC.FileTime.Forms.Form_Main.StartUpMode3 (string targetPath, string comparePath) inline private
Mode 3. Recursive, file Tree time compare mode. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-compare-the-contents-of-two-folders-linq
Definition at line 384 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode3().
void genBTC.FileTime.Forms.Form_Main.PrepareDataModelForUse () inline private
Resets the files-to-confirm list, Skips count, reads GUIstatus data (radios), reads CMA checkboxes (lazy/dupe gui fields)
Definition at line 396 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.checkboxes, genBTC.FileTime.Models.DataModel.FilestoConfirmList, genBTC.FileTime.Models.DataModel.gui, genBTC.FileTime.Models.SkippedHSR.Reset(), and genBTC.FileTime.Models.DataModel.Skips.
void genBTC.FileTime.Forms.Form_Main.StartUpBothModes1And2 (int mode2, string startingdir) inline private
Launches Mode 1 and Mode 2. This runs a LONG process on the folders/files. It decides which time to use, then adds them to the confirm list to be handled by the form_confirm window (part2). Cant move into the model. This is a nice staging point place for making EVERYTHING happen.
Definition at line 409 of file Form_Main.cs.
References genBTC.FileTime.Models.DataModel.AddONEFiletoConfirmList(), genBTC.FileTime.Models.DataModel.DecideWhichTimeMode1(), genBTC.FileTime.Properties.Settings.Default, genBTC.FileTime.Models.Directory, genBTC.FileTime.Models.DataModel.fixreadonlyActive, genBTC.FileTime.Models.DataModel.FixReadonlyResults(), genBTC.FileTime.Properties.Settings.mode1addrootdir, genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode1(), genBTC.FileTime.Models.DataModel.RecurseSubDirectoryMode2(), and genBTC.FileTime.Properties.Settings.useRootDirAsContainer.
void genBTC.FileTime.Forms.Form_Main.LaunchForm2Go () inline private
Show files to be changed in the confirmation window (Show Form 2)
Definition at line 477 of file Form_Main.cs.
References genBTC.FileTime.Models.SkippedHSR.H, genBTC.FileTime.Forms.Form_Confirm.MakeListView(), genBTC.FileTime.Models.SkippedHSR.R, genBTC.FileTime.Models.SkippedHSR.S, and genBTC.FileTime.Models.DataModel.Skips.
void genBTC.FileTime.Forms.Form_Main.label_folderCompareRadioButton_Click (object sender, EventArgs e) inline private
Definition at line 497 of file Form_Main.cs.
override void genBTC.FileTime.Forms.Form_Main.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 17 of file Form_Main.Designer.cs.
void genBTC.FileTime.Forms.Form_Main.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 88 of file Form_Main.Designer.cs.
Field Documentation
DataModel genBTC.FileTime.Forms.Form_Main._dataModel package
A model of the data. Self sufficient.
Definition at line 67 of file Form_Main.cs.
Form_Confirm genBTC.FileTime.Forms.Form_Main.Confirmation
Stub for Form 2 to be accessed once it is opened.
Definition at line 70 of file Form_Main.cs.
readonly Timer genBTC.FileTime.Forms.Form_Main._itemSelectionChangedTimer = new Timer() private
a Timer to keep track of the selected line, prevents clicking too fast (timeout)
Definition at line 73 of file Form_Main.cs.
const int genBTC.FileTime.Forms.Form_Main.SELECTION_TIMEOUT = 100 private
Timeout in ms for ListView selection-box's repeat mouse click rejection
Definition at line 75 of file Form_Main.cs.
System.ComponentModel.IContainer genBTC.FileTime.Forms.Form_Main.components = null private
Required designer variable.
Definition at line 11 of file Form_Main.Designer.cs.
Button genBTC.FileTime.Forms.Form_Main.button_Browse private
Definition at line 29 of file Form_Main.Designer.cs.
MainMenu genBTC.FileTime.Forms.Form_Main.mainMenu_Main private
Definition at line 30 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_FileExit private
Definition at line 31 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_Help private
Definition at line 32 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_HelpAbout private
Definition at line 33 of file Form_Main.Designer.cs.
Button genBTC.FileTime.Forms.Form_Main.button_GoUpdate private
Definition at line 34 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_FileOpen private
Definition at line 35 of file Form_Main.Designer.cs.
CheckBox genBTC.FileTime.Forms.Form_Main.checkBox_CreationDateTime private
Definition at line 36 of file Form_Main.Designer.cs.
CheckBox genBTC.FileTime.Forms.Form_Main.checkBox_AccessedDateTime private
Definition at line 37 of file Form_Main.Designer.cs.
CheckBox genBTC.FileTime.Forms.Form_Main.checkBox_ModifiedDateTime private
Definition at line 38 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_FPath private
Definition at line 39 of file Form_Main.Designer.cs.
DateTimePicker genBTC.FileTime.Forms.Form_Main.dateTimePicker_Time private
Definition at line 40 of file Form_Main.Designer.cs.
ImageList genBTC.FileTime.Forms.Form_Main.imageList_Files private
Definition at line 41 of file Form_Main.Designer.cs.
CheckBox genBTC.FileTime.Forms.Form_Main.checkBox_Recurse private
Definition at line 42 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_File private
Definition at line 43 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_FileBar01 private
Definition at line 44 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_HelpContents private
Definition at line 45 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_HelpBar01 private
Definition at line 46 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_FilePathHeading private
Definition at line 47 of file Form_Main.Designer.cs.
DateTimePicker genBTC.FileTime.Forms.Form_Main.dateTimePicker_Date private
Definition at line 48 of file Form_Main.Designer.cs.
ListView genBTC.FileTime.Forms.Form_Main.listView_Contents private
Definition at line 49 of file Form_Main.Designer.cs.
ColumnHeader genBTC.FileTime.Forms.Form_Main.listview_ContentsColumHeader1 private
Definition at line 50 of file Form_Main.Designer.cs.
CheckBox genBTC.FileTime.Forms.Form_Main.checkBoxShouldFiles private
Definition at line 51 of file Form_Main.Designer.cs.
GroupBox genBTC.FileTime.Forms.Form_Main.groupBoxCMA private
Definition at line 52 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton1_CreationDate private
Definition at line 53 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_CreationTime private
Definition at line 54 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton2_ModifiedDate private
Definition at line 55 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_ModificationTime private
Definition at line 56 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton3_AccessedDate private
Definition at line 57 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_AccessedTime private
Definition at line 58 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton3_setfromAccessed private
Definition at line 59 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton2_setfromModified private
Definition at line 60 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton1_setfromCreation private
Definition at line 61 of file Form_Main.Designer.cs.
UIToolbox.RadioButtonPanel genBTC.FileTime.Forms.Form_Main.radioButtonPanel1_DecideWhichTime private
Definition at line 62 of file Form_Main.Designer.cs.
UIToolbox.RadioGroupBox genBTC.FileTime.Forms.Form_Main.radioGroupBox3_UseTimeFrom private
Definition at line 63 of file Form_Main.Designer.cs.
UIToolbox.RadioGroupBox genBTC.FileTime.Forms.Form_Main.radioGroupBox1_SpecifyTime private
Definition at line 64 of file Form_Main.Designer.cs.
Panel genBTC.FileTime.Forms.Form_Main.panel1 private
Definition at line 65 of file Form_Main.Designer.cs.
Panel genBTC.FileTime.Forms.Form_Main.panel2 private
Definition at line 66 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton3_Random private
Definition at line 67 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton2_Newest private
Definition at line 68 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton1_Oldest private
Definition at line 69 of file Form_Main.Designer.cs.
UIToolbox.RadioGroupBox genBTC.FileTime.Forms.Form_Main.radioGroupBox2_CurrentSelectionTime private
Definition at line 70 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label3_AccessedDate private
Definition at line 71 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label2_ModifiedDate private
Definition at line 72 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label1_CreationDate private
Definition at line 73 of file Form_Main.Designer.cs.
UIToolbox.RadioButtonPanel genBTC.FileTime.Forms.Form_Main.radioButtonPanel2 private
Definition at line 74 of file Form_Main.Designer.cs.
Panel genBTC.FileTime.Forms.Form_Main.panel3 private
Definition at line 75 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton2_useTimefromSubdir private
Definition at line 76 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton1_useTimefromFile private
Definition at line 77 of file Form_Main.Designer.cs.
RadioButton genBTC.FileTime.Forms.Form_Main.radioButton4_setfromRandom private
Definition at line 78 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.labelHidden_PathName private
Definition at line 79 of file Form_Main.Designer.cs.
MenuItem genBTC.FileTime.Forms.Form_Main.menuItem_Preferences private
Definition at line 867 of file Form_Main.Designer.cs.
TabControl genBTC.FileTime.Forms.Form_Main.tabControl1 private
Definition at line 868 of file Form_Main.Designer.cs.
TabPage genBTC.FileTime.Forms.Form_Main.tabPage1 private
Definition at line 869 of file Form_Main.Designer.cs.
TabPage genBTC.FileTime.Forms.Form_Main.tabPage2 private
Definition at line 870 of file Form_Main.Designer.cs.
ToolTip genBTC.FileTime.Forms.Form_Main.toolTip1 private
Definition at line 871 of file Form_Main.Designer.cs.
WindowsExplorer.ExplorerTree genBTC.FileTime.Forms.Form_Main.explorerTree1 private
Definition at line 872 of file Form_Main.Designer.cs.
SplitContainer genBTC.FileTime.Forms.Form_Main.splitContainer1 private
Definition at line 873 of file Form_Main.Designer.cs.
UIToolbox.RadioGroupBox genBTC.FileTime.Forms.Form_Main.radioGroupBox4_pickFolderForCompare private
Definition at line 874 of file Form_Main.Designer.cs.
Label genBTC.FileTime.Forms.Form_Main.label_folderCompareRadioButton private
Definition at line 875 of file Form_Main.Designer.cs.
BindingSource genBTC.FileTime.Forms.Form_Main.dataModelBindingSource private
Definition at line 876 of file Form_Main.Designer.cs.
Property Documentation
string genBTC.FileTime.Forms.Form_Main.CwdPathName get set
Public Setter to the private variable in Datamodel.
Definition at line 104 of file Form_Main.cs.
The documentation for this class was generated from the following files:
Form_Main.cs
Form_Main.Designer.cs