genBTC FileTime: WindowsExplorer.ExplorerTree Class Reference
WindowsExplorer.ExplorerTree Class Reference
Summary description for ExplorerTree.
Public Member Functions
ExplorerTree ()
Explorer-Like TreeView control.
void RefreshControlUi ()
Refresh the Control itself (toolbar, etc) (public)
void InitialPopulate ()
Initially Populate the Treeview (public)
void SelectRootNode ()
Select and scroll to the topmost node (Desktop), after it has been initialized.
void SetCurrentPath (string strPath)
Set the path in the textbox, and fires the path changed event... Call BrowseTo() afterwards to go to it.
void RefreshFolders ()
Refresh Button - Re-Initialize the TreeView from the beginning (Desktop).
void BrowseTo ()
Navigate the treeview to the path in the textbox. Must be called manually when CurrentPath changes.
delegate void PathChangedEventHandler (object sender, EventArgs e)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
string CurrentPath [get, set]
Startup Path, what is shown in text box.
bool GoFlag [get, set]
bool ShowAddressbar [get, set]
bool ShowMyDocuments [get, set]
bool ShowMyFavorites [get, set]
bool ShowMyNetwork [get, set]
bool ShowToolbar [get, set]
PathChangedEventHandler PathChanged
Event that fires when the textbox path changes(including but not limited to after a node selection), but only if the directory is valid.
Private Member Functions
void ExplorerTree_Load (object sender, EventArgs e)
void txtPath_TextChanged (object sender, EventArgs e)
Fires after every character is typed, or an item is selected.
void PopulateMyComputer ()
void tvwMain_AfterExpand (object sender, TreeViewEventArgs e)
void tvwMain_AfterSelect (object sender, TreeViewEventArgs e)
Updates path textbox after selectionchange
void tvwMain_DoubleClick (object sender, EventArgs e)
Event for collapse/expand
void btnRefresh_Click (object sender, EventArgs e)
void btnGo_Click (object sender, EventArgs e)
The event handler for when the actual button is clicked.
void btnHome_Click (object sender, EventArgs e)
void btnNext_Click (object sender, EventArgs e)
void btnBack_Click (object sender, EventArgs e)
void tvwMain_MouseUp (object sender, MouseEventArgs e)
void btnUp_Click (object sender, EventArgs e)
void btnAdd_Click (object sender, EventArgs e)
void AddFolderNode (string name, string path)
void mnuShortcut_Click (object sender, EventArgs e)
void txtPath_KeyUp (object sender, KeyEventArgs e)
void btnInfo_Click (object sender, EventArgs e)
void UpdateListAddCurrent ()
void UpdateListGoBack ()
void UpdateListGoFwd ()
void UpdateList (string f)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static void ExploreTreeNode (TreeNode n, bool isInitial=false)
static void GetDirectories (TreeNode node, bool isInitial=false)
Private Attributes
TreeNode nodeEntireNetwork
TreeNode nodeMyComputer
TreeNode nodeMyDocuments
TreeNode rootnodeDesktop
System.ComponentModel.IContainer components
Button btnAdd
Button btnGo
Button btnRefresh
Button btnHome
Button btnBack
Button btnNext
Button btnUp
Button btnInfo
ToolTip toolTip1
ListView listView1
ColumnHeader column1_Path
ColumnHeader column2_Status
ImageList imageList1
ContextMenu cMShortcut
MenuItem mnuShortcut
TextBox txtPath
GroupBox grptoolbar
TreeView treeview1
PathChangedEventHandler PathChangedEvent
Static Private Attributes
static readonly string Seperator = Path.DirectorySeparatorChar.ToString()
static readonly string Desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)
static readonly string MyDocuments = Environment.GetFolderPath(Environment.SpecialFolder.Personal)
static readonly string Favorites = Environment.GetFolderPath(Environment.SpecialFolder.Favorites)
Detailed Description
Summary description for ExplorerTree.
Definition at line 24 of file ExplorerTree.cs.
Constructor & Destructor Documentation
WindowsExplorer.ExplorerTree.ExplorerTree () inline
Explorer-Like TreeView control.
Definition at line 36 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.InitializeComponent().
Member Function Documentation
void WindowsExplorer.ExplorerTree.ExplorerTree_Load (object sender, EventArgs e) inline private
Definition at line 64 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.InitialPopulate(), and WindowsExplorer.ExplorerTree.RefreshControlUi().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.RefreshControlUi () inline
Refresh the Control itself (toolbar, etc) (public)
Definition at line 73 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo, WindowsExplorer.ExplorerTree.grptoolbar, WindowsExplorer.ExplorerTree.ShowAddressbar, WindowsExplorer.ExplorerTree.ShowToolbar, WindowsExplorer.ExplorerTree.treeview1, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.btnRefresh_Click(), and WindowsExplorer.ExplorerTree.ExplorerTree_Load().
void WindowsExplorer.ExplorerTree.InitialPopulate () inline
Initially Populate the Treeview (public)
Definition at line 119 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.Desktop, WindowsExplorer.ExplorerTree.ExploreTreeNode(), WindowsExplorer.ExplorerTree.Favorites, WindowsExplorer.ExplorerTree.GetDirectories(), WindowsExplorer.ExplorerTree.MyDocuments, WindowsExplorer.ExplorerTree.ShowMyDocuments, WindowsExplorer.ExplorerTree.ShowMyFavorites, WindowsExplorer.ExplorerTree.ShowMyNetwork, and WindowsExplorer.ExplorerTree.treeview1.
Referenced by WindowsExplorer.ExplorerTree.ExplorerTree_Load(), and WindowsExplorer.ExplorerTree.RefreshFolders().
static void WindowsExplorer.ExplorerTree.ExploreTreeNode (TreeNode n, bool isInitial = false) inline static private
Definition at line 204 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.GetDirectories().
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate(), WindowsExplorer.ExplorerTree.tvwMain_AfterExpand(), and WindowsExplorer.ExplorerTree.tvwMain_DoubleClick().
static void WindowsExplorer.ExplorerTree.GetDirectories (TreeNode node, bool isInitial = false) inline static private
Definition at line 216 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.ExploreTreeNode(), and WindowsExplorer.ExplorerTree.InitialPopulate().
void WindowsExplorer.ExplorerTree.SelectRootNode () inline
Select and scroll to the topmost node (Desktop), after it has been initialized.
Definition at line 254 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.rootnodeDesktop, and WindowsExplorer.ExplorerTree.treeview1.
void WindowsExplorer.ExplorerTree.SetCurrentPath (string strPath) inline
Set the path in the textbox, and fires the path changed event... Call BrowseTo() afterwards to go to it.
Definition at line 263 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.CurrentPath, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.btnHome_Click(), and WindowsExplorer.ExplorerTree.RefreshFolders().
void WindowsExplorer.ExplorerTree.txtPath_TextChanged (object sender, EventArgs e) inline private
Fires after every character is typed, or an item is selected.
Definition at line 273 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.CurrentPath, WindowsExplorer.ExplorerTree.PathChangedEvent, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.PopulateMyComputer () inline private
Definition at line 282 of file ExplorerTree.cs.
References WindowsExplorer.Kernel32.GetDriveType().
Referenced by WindowsExplorer.ExplorerTree.BrowseTo(), WindowsExplorer.ExplorerTree.btnHome_Click(), and WindowsExplorer.ExplorerTree.tvwMain_AfterExpand().
void WindowsExplorer.ExplorerTree.tvwMain_AfterExpand (object sender, TreeViewEventArgs e) inline private
Definition at line 357 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.ExploreTreeNode(), and WindowsExplorer.ExplorerTree.PopulateMyComputer().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.tvwMain_AfterSelect (object sender, TreeViewEventArgs e) inline private
Updates path textbox after selectionchange
Definition at line 473 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.tvwMain_DoubleClick (object sender, EventArgs e) inline private
Event for collapse/expand
Definition at line 481 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.ExploreTreeNode(), and WindowsExplorer.ExplorerTree.treeview1.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.RefreshFolders () inline
Refresh Button - Re-Initialize the TreeView from the beginning (Desktop).
Definition at line 497 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.InitialPopulate(), WindowsExplorer.ExplorerTree.listView1, WindowsExplorer.ExplorerTree.SetCurrentPath(), and WindowsExplorer.ExplorerTree.treeview1.
Referenced by WindowsExplorer.ExplorerTree.btnRefresh_Click().
void WindowsExplorer.ExplorerTree.btnRefresh_Click (object sender, EventArgs e) inline private
Definition at line 505 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.RefreshControlUi(), and WindowsExplorer.ExplorerTree.RefreshFolders().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnGo_Click (object sender, EventArgs e) inline private
The event handler for when the actual button is clicked.
Definition at line 516 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.BrowseTo().
Referenced by WindowsExplorer.ExplorerTree.btnBack_Click(), WindowsExplorer.ExplorerTree.btnHome_Click(), WindowsExplorer.ExplorerTree.btnNext_Click(), WindowsExplorer.ExplorerTree.btnUp_Click(), WindowsExplorer.ExplorerTree.InitializeComponent(), and WindowsExplorer.ExplorerTree.txtPath_KeyUp().
void WindowsExplorer.ExplorerTree.BrowseTo () inline
Navigate the treeview to the path in the textbox. Must be called manually when CurrentPath changes.
Definition at line 524 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.nodeEntireNetwork, WindowsExplorer.ExplorerTree.nodeMyComputer, WindowsExplorer.ExplorerTree.nodeMyDocuments, WindowsExplorer.ExplorerTree.PopulateMyComputer(), WindowsExplorer.ExplorerTree.rootnodeDesktop, genBTC.FileTime.Classes.Native.NativeScroll.ScrollH(), WindowsExplorer.ExplorerTree.treeview1, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.btnGo_Click().
void WindowsExplorer.ExplorerTree.btnHome_Click (object sender, EventArgs e) inline private
Definition at line 630 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo_Click(), WindowsExplorer.ExplorerTree.PopulateMyComputer(), and WindowsExplorer.ExplorerTree.SetCurrentPath().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnNext_Click (object sender, EventArgs e) inline private
Definition at line 637 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo_Click(), WindowsExplorer.ExplorerTree.GoFlag, WindowsExplorer.ExplorerTree.txtPath, and WindowsExplorer.ExplorerTree.UpdateListGoFwd().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnBack_Click (object sender, EventArgs e) inline private
Definition at line 648 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo_Click(), WindowsExplorer.ExplorerTree.GoFlag, WindowsExplorer.ExplorerTree.txtPath, and WindowsExplorer.ExplorerTree.UpdateListGoBack().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.tvwMain_MouseUp (object sender, MouseEventArgs e) inline private
Definition at line 659 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.cMShortcut, WindowsExplorer.ExplorerTree.treeview1, WindowsExplorer.ExplorerTree.txtPath, and WindowsExplorer.ExplorerTree.UpdateList().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnUp_Click (object sender, EventArgs e) inline private
Definition at line 667 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo_Click(), WindowsExplorer.ExplorerTree.txtPath, and WindowsExplorer.ExplorerTree.UpdateList().
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnAdd_Click (object sender, EventArgs e) inline private
Definition at line 684 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.AddFolderNode(), and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.AddFolderNode (string name, string path) inline private
Definition at line 702 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.btnAdd_Click().
void WindowsExplorer.ExplorerTree.mnuShortcut_Click (object sender, EventArgs e) inline private
Definition at line 737 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.treeview1.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.txtPath_KeyUp (object sender, KeyEventArgs e) inline private
Definition at line 743 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.btnGo_Click(), and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.btnInfo_Click (object sender, EventArgs e) inline private
Definition at line 752 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
void WindowsExplorer.ExplorerTree.UpdateListAddCurrent () inline private
Definition at line 756 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.listView1.
Referenced by WindowsExplorer.ExplorerTree.UpdateList().
void WindowsExplorer.ExplorerTree.UpdateListGoBack () inline private
Definition at line 770 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.listView1, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.btnBack_Click().
void WindowsExplorer.ExplorerTree.UpdateListGoFwd () inline private
Definition at line 789 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.listView1, and WindowsExplorer.ExplorerTree.txtPath.
Referenced by WindowsExplorer.ExplorerTree.btnNext_Click().
void WindowsExplorer.ExplorerTree.UpdateList (string f) inline private
Definition at line 809 of file ExplorerTree.cs.
References WindowsExplorer.ExplorerTree.listView1, and WindowsExplorer.ExplorerTree.UpdateListAddCurrent().
Referenced by WindowsExplorer.ExplorerTree.btnUp_Click(), and WindowsExplorer.ExplorerTree.tvwMain_MouseUp().
delegate void WindowsExplorer.ExplorerTree.PathChangedEventHandler (object sender, EventArgs e)
override void WindowsExplorer.ExplorerTree.Dispose (bool disposing) inline protected
Clean up any resources being used.
Definition at line 63 of file ExplorerTree.Designer.cs.
References WindowsExplorer.ExplorerTree.components.
void WindowsExplorer.ExplorerTree.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 79 of file ExplorerTree.Designer.cs.
References WindowsExplorer.ExplorerTree.btnAdd_Click(), WindowsExplorer.ExplorerTree.btnBack_Click(), WindowsExplorer.ExplorerTree.btnGo_Click(), WindowsExplorer.ExplorerTree.btnHome_Click(), WindowsExplorer.ExplorerTree.btnInfo_Click(), WindowsExplorer.ExplorerTree.btnNext_Click(), WindowsExplorer.ExplorerTree.btnRefresh_Click(), WindowsExplorer.ExplorerTree.btnUp_Click(), WindowsExplorer.ExplorerTree.components, WindowsExplorer.ExplorerTree.ExplorerTree_Load(), WindowsExplorer.ExplorerTree.imageList1, WindowsExplorer.ExplorerTree.mnuShortcut_Click(), WindowsExplorer.ExplorerTree.tvwMain_AfterExpand(), WindowsExplorer.ExplorerTree.tvwMain_AfterSelect(), WindowsExplorer.ExplorerTree.tvwMain_DoubleClick(), WindowsExplorer.ExplorerTree.tvwMain_MouseUp(), WindowsExplorer.ExplorerTree.txtPath_KeyUp(), and WindowsExplorer.ExplorerTree.txtPath_TextChanged().
Referenced by WindowsExplorer.ExplorerTree.ExplorerTree().
Field Documentation
readonly string WindowsExplorer.ExplorerTree.Seperator = Path.DirectorySeparatorChar.ToString() static private
Definition at line 26 of file ExplorerTree.cs.
readonly string WindowsExplorer.ExplorerTree.Desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) static private
Definition at line 27 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
readonly string WindowsExplorer.ExplorerTree.MyDocuments = Environment.GetFolderPath(Environment.SpecialFolder.Personal) static private
Definition at line 28 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
readonly string WindowsExplorer.ExplorerTree.Favorites = Environment.GetFolderPath(Environment.SpecialFolder.Favorites) static private
Definition at line 29 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
TreeNode WindowsExplorer.ExplorerTree.nodeEntireNetwork private
Definition at line 30 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo().
TreeNode WindowsExplorer.ExplorerTree.nodeMyComputer private
Definition at line 31 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo().
TreeNode WindowsExplorer.ExplorerTree.nodeMyDocuments private
Definition at line 32 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo().
TreeNode WindowsExplorer.ExplorerTree.rootnodeDesktop private
Definition at line 33 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo(), and WindowsExplorer.ExplorerTree.SelectRootNode().
System.ComponentModel.IContainer WindowsExplorer.ExplorerTree.components private
Definition at line 22 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.Dispose(), and WindowsExplorer.ExplorerTree.InitializeComponent().
Button WindowsExplorer.ExplorerTree.btnAdd private
Definition at line 23 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnGo private
Definition at line 24 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.RefreshControlUi().
Button WindowsExplorer.ExplorerTree.btnRefresh private
Definition at line 25 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnHome private
Definition at line 26 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnBack private
Definition at line 27 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnNext private
Definition at line 28 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnUp private
Definition at line 29 of file ExplorerTree.Designer.cs.
Button WindowsExplorer.ExplorerTree.btnInfo private
Definition at line 30 of file ExplorerTree.Designer.cs.
ToolTip WindowsExplorer.ExplorerTree.toolTip1 private
Definition at line 31 of file ExplorerTree.Designer.cs.
ListView WindowsExplorer.ExplorerTree.listView1 private
Definition at line 32 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.RefreshFolders(), WindowsExplorer.ExplorerTree.UpdateList(), WindowsExplorer.ExplorerTree.UpdateListAddCurrent(), WindowsExplorer.ExplorerTree.UpdateListGoBack(), and WindowsExplorer.ExplorerTree.UpdateListGoFwd().
ColumnHeader WindowsExplorer.ExplorerTree.column1_Path private
Definition at line 33 of file ExplorerTree.Designer.cs.
ColumnHeader WindowsExplorer.ExplorerTree.column2_Status private
Definition at line 34 of file ExplorerTree.Designer.cs.
ImageList WindowsExplorer.ExplorerTree.imageList1 private
Definition at line 35 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.InitializeComponent().
ContextMenu WindowsExplorer.ExplorerTree.cMShortcut private
Definition at line 36 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.tvwMain_MouseUp().
MenuItem WindowsExplorer.ExplorerTree.mnuShortcut private
Definition at line 37 of file ExplorerTree.Designer.cs.
TextBox WindowsExplorer.ExplorerTree.txtPath private
Definition at line 38 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo(), WindowsExplorer.ExplorerTree.btnAdd_Click(), WindowsExplorer.ExplorerTree.btnBack_Click(), WindowsExplorer.ExplorerTree.btnNext_Click(), WindowsExplorer.ExplorerTree.btnUp_Click(), WindowsExplorer.ExplorerTree.RefreshControlUi(), WindowsExplorer.ExplorerTree.SetCurrentPath(), WindowsExplorer.ExplorerTree.tvwMain_AfterSelect(), WindowsExplorer.ExplorerTree.tvwMain_MouseUp(), WindowsExplorer.ExplorerTree.txtPath_KeyUp(), WindowsExplorer.ExplorerTree.txtPath_TextChanged(), WindowsExplorer.ExplorerTree.UpdateListGoBack(), and WindowsExplorer.ExplorerTree.UpdateListGoFwd().
GroupBox WindowsExplorer.ExplorerTree.grptoolbar private
Definition at line 39 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.RefreshControlUi().
TreeView WindowsExplorer.ExplorerTree.treeview1 private
Definition at line 40 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.BrowseTo(), WindowsExplorer.ExplorerTree.InitialPopulate(), WindowsExplorer.ExplorerTree.mnuShortcut_Click(), WindowsExplorer.ExplorerTree.RefreshControlUi(), WindowsExplorer.ExplorerTree.RefreshFolders(), WindowsExplorer.ExplorerTree.SelectRootNode(), WindowsExplorer.ExplorerTree.tvwMain_DoubleClick(), and WindowsExplorer.ExplorerTree.tvwMain_MouseUp().
PathChangedEventHandler WindowsExplorer.ExplorerTree.PathChangedEvent private
Definition at line 43 of file ExplorerTree.Designer.cs.
Referenced by WindowsExplorer.ExplorerTree.txtPath_TextChanged().
Property Documentation
string WindowsExplorer.ExplorerTree.CurrentPath get set
Startup Path, what is shown in text box.
Definition at line 50 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.SetCurrentPath(), and WindowsExplorer.ExplorerTree.txtPath_TextChanged().
bool WindowsExplorer.ExplorerTree.GoFlag get set private
Definition at line 52 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.btnBack_Click(), and WindowsExplorer.ExplorerTree.btnNext_Click().
bool WindowsExplorer.ExplorerTree.ShowAddressbar get set
Definition at line 54 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.RefreshControlUi().
bool WindowsExplorer.ExplorerTree.ShowMyDocuments get set
Definition at line 56 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
bool WindowsExplorer.ExplorerTree.ShowMyFavorites get set
Definition at line 58 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
bool WindowsExplorer.ExplorerTree.ShowMyNetwork get set
Definition at line 60 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.InitialPopulate().
bool WindowsExplorer.ExplorerTree.ShowToolbar get set
Definition at line 62 of file ExplorerTree.cs.
Referenced by WindowsExplorer.ExplorerTree.RefreshControlUi().
PathChangedEventHandler WindowsExplorer.ExplorerTree.PathChanged add remove
Event that fires when the textbox path changes(including but not limited to after a node selection), but only if the directory is valid.
Definition at line 49 of file ExplorerTree.Designer.cs.
The documentation for this class was generated from the following files:
ExplorerTree.cs
ExplorerTree.Designer.cs